server:
  port: 8082

spring:
  application:
    name: config-order-service
  cloud:
    nacos:
      serverAddr: 192.168.1.2:8848
  config:
    import:
      - nacos:test.yaml?refresh=true

dubbo:
  protocol:
    name: dubbo
    port: -1
  application:
    name: dubbo-order-service
  registry:
    address: nacos://192.168.1.2:8848